### ISSUE TITLE
More info desired

### ISSUE THREAD

**Issue by jmakin-godaddy** [L-Spiro/Nintendo-Synthy-4#1]
Please bulk up the description and/or add a readme.
Does this just build on windows, or can it be built on linux? If so, please state how.
Do you have any screenshots or demos of it running/playing?

Great projects like this should be seen by more people.

**Comment by L-Spiro** [comment]
The problem is that right now not only is there no UI, strings and things are temporarily hardcoded etc.  It has to be rebuilt to run/export a new OST.
This is obviously extremely temporary; I’m working on the parser I want to use to parse project files—which will make it usable by others—and then after that I will make a UI.  Screenshots will come after that, along with everything else you requested, it’s just that right now it’s a premature baby that isn’t ready for exposure.  Once it is ready for the big time I will spice the whole place up with screenshots, descriptions, directions, etc.

To answer your question about Linux, I don’t have the platform and can’t say for sure, but in theory it should be a matter of removing the LSWindows library (which is currently unused; it is just sitting there waiting to be used) and then fixing any minor errors that appear.  `::QueryPerformanceCounter()` and `::QueryPerformanceFrequency()` need to be replaced and debug comments using `::OutputDebugStringA()` need to be commented out.  Other than that it’s standard C++, so any remaining issues are expected to just be differences in the compilers and easy to handle.

**Comment by jmakin-godaddy** [comment]
I see. I didn't realise how modern a project it was until now. First commit only August!
